### ISSUE TITLE
Production build failing

### ISSUE THREAD

**Issue by li0nza** [Independer/ng-modal#8]
Hi.

I cannot get my project to do a `ng build --prod` with `ng-modal`.  A normal `ng build` works perfectly fine.  I have tried digging around to find out what is wrong, but have failed to get a solution, could you guys please assist?

`ERROR in ./node_modules/@independer/ng-modal/modal.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\node_modules\@independer\ng-modal'

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app'

ERROR in ./src/app/components/events/list/list.component.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app\components\events\list'

ERROR in ./src/app/components/services/list/list.component.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app\components\services\list'

ERROR in ./src/app/components/services/view-log/view-log.component.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app\components\services\view-log'

ERROR in ./src/app/components/user-management/list/list.component.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app\components\user-management\list'

ERROR in ./src/app/components/user-management/register/register.component.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app\components\user-management\register'

ERROR in ./src/app/components/user-management/update/update.component.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app\components\user-management\update'

ERROR in ./src/app/shared/confirmation/confirmation.component.ngfactory.js
Module not found: Error: Can't resolve 'modal' in 'D:\Projects\...\src\app\shared\confirmation'`

**Comment by pglazkov** [comment]
Thank you for your report and sorry for the delay. This is now fixed in version 1.2.2.
